apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-v1
  name: app-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-v1
    spec:
      initContainers:
      - name: install
        image: busybox
        command: 
        - bin/sh
        - -c
        - echo "version 1" > /work-dir/index.html
        volumeMounts:
        - name: workdir
          mountPath: /work-dir
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      volumes:
      - name: workdir
        emptyDir: {}
status: {}
