apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cube-test
  name: cube-test
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: accelerator
            operator: In
            values:
            - nvidia-tesla-p100
  containers:
  - image: nginx
    name: cube-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

status: {}
