apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx6
  name: nginx6
spec:
  initContainers:
  - args:
    - /bin/sh
    - -c
    - wget -O /work-dir/index.html http://neverssl.com/online
    image: busybox
    name: nginx-1
    volumeMounts:
    - mountPath: /work-dir
      name: vol
    resources: {}
  containers:
  - image: nginx
    name: nginx6
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: vol
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never

  volumes:
  - name: vol
    emptyDir: {}
status: {}
