apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx5
  name: nginx5
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: nginx-1
    resources: {}
  - args:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: nginx-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
